spring:
  profiles.active: production
---
spring:
  profiles: dev
logging:
  file: D:/log/helloworld.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.example.*: DEBUG
---
spring:
  profiles: production
logging:
  file: D:/log/helloworld.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    com.example.*: WARN
     
    